# What is NumPy?

- NumPy stands for Numerical Python and is an excellent way to deal with arrays and large amount of data in general within python.
- NumPy provides efficeint storage, it also provides better ways of handling data for processing. 
- pip install numpy - using this command in our command prompt/terminal we can install numpy in our environment.
- import numpy as np - this means that the code is bringing in the NumPy library and 'np' is an alias for numpy, making it more easier to read and write.

### Why NumPy is Faster than List?

- NumPy arrays are stored at one continuous place in memory unlike list, so processes can access and manipulate them very efficiently.

### Application of Numpy

1. An alternative for list in python.
2. Mathematical operations
3. Plotting (Matplotlib)
4. Backend (Pandas, Digital photography)

### What is array?

- In computer programming, an array is a structure for storing and retrieving data.
- We might visualize a one-dimensional array is like a list, two dimensional array is like a table, three dimensional array is like a set of tables and N-dimensional array is called 'ndarray'.

### What is the difference between Array and List?

- All elements of the array must be of the same type of data.
- Arrays are faster and more memory efficient.
- Arrays are suitable for storing large sequence of data items.
- Once created, the total size of the array can't change.
- The shape must be 'rectangular' not 'jagged'; e.g. each row of  a two-dimensional array must have the same number of columns.


### Array Creation

1. Conversion from Python Structures (i.e. lists and tuples)
2. Intrinsic numpy array creation functions (i.e. np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace())

##### *1. Conversion from Python Structures*

In [168]:
import numpy as np

In [169]:
# One-Dimensional Array from Python List

a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [170]:
# Two-Dimensional Array from Python Nested List

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
# Three-Dimensional Array from Python Nested List

a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [172]:
# One-Dimensional Array from Python tuple

b = np.array((1, 2, 3, 4, 5))
b

array([1, 2, 3, 4, 5])

In [173]:
# Two-Dimensional Array from python Nested Tuple

b = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 9)))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [174]:
# Three-Dimensional Array from Python Nested Tuple

data = (
    (
        (1, 2, 3), 
        (4, 5, 6), 
        (7, 8, 9)
    ),
    (
        (11, 12, 13),
        (14, 15, 16),
        (17, 18, 19)
    ),
    (
        (21, 22, 23),
        (24, 25, 26),
        (27, 28, 29)
    )

        )

b = np.array(data)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

##### *2. Intrinsic numpy array creation functions*

2.1. Zeros

The function np.zeros() in NumPy creates an array filled with zero. You can specify the shape of array in a tuple.

- np.zeros(value)         - one dimensional
- np.zeros((row_value, column_value))         - two dimensional

In [175]:
a = np.zeros(1)
a

array([0.])

In [176]:
b = np.zeros(2)
b

array([0., 0.])

In [177]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [178]:
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [179]:
e = np.zeros((3,3))
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2.2. Ones

The function np.ones() in NumPy creates an array filled with one. Similar to np.zeros() you can specify the shape of the array using a tuple.

- np.ones(value)         - one dimensional
- np.ones((row_value, column_value))         - two dimensional

In [180]:
np.ones(1)


array([1.])

In [181]:
np.ones(2)

array([1., 1.])

In [182]:
np.ones(3)

array([1., 1., 1.])

In [183]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [184]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

2.3. Empty

The np.empty() function is used to create a new array with given shape and type, without intializing entries.

- np.empty(value)
- np.empty(value, dtype=int)      - with int data type
- np.empty([row_value, column_value], dtype=int)      - two-dimensional with data type

In [185]:
np.empty(2)

array([1., 1.])

In [186]:
np.empty(3, dtype=int)

array([4607182418800017408, 4607182418800017408, 4607182418800017408])

In [187]:
np.empty(3, dtype=float)

array([1., 1., 1.])

In [188]:
np.empty(3, dtype=str)

array(['', '', ''], dtype='<U1')

In [189]:
np.empty([2,3], dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [190]:
np.empty((3,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

2.4. Arange

np.arange() is a function in numpy  that generates an array of evenly spaced values within a specified range. It is similar to pythons build in range() function, but it returns a numpy array instead of list.

np.arange(value)

In [191]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [192]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

Difference between range() and arange()

• range:
- range is python's built-in function.
- best for generate a small range of integers.
- it is memory efficient because it generates numbers on the fly.

• arange:
- arrange is python's function from numpy library.
- best for generate a large range of floating point numbers.
- it consumes more memory than range().

2.5. Linspace

np.linspace() is a function in numpy that generates an array of evenly spaced values over a specified range. Unlike np.arange(), which uses a specified step size, np.linspace() allows you to specify the number of points you want in the interval.

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

    start   - The starting value of the sequence.
    stop    - The end value of the sequence.
    num     - The number of samples to generate (default is 50).
    endpoint- If True (default), stop is included in the output. If False, it is not included.
    retstep - If True, the function returns both the array of samples and the spacing between samples.
    dtype   - The desired data type for the array (optional).

In [194]:
np.linspace(5, 50, num=10, endpoint=False)

array([ 5. ,  9.5, 14. , 18.5, 23. , 27.5, 32. , 36.5, 41. , 45.5])

In [195]:
arr, step = np.linspace(5, 50, num=10, endpoint=False, retstep=True)
print(arr)
print(step)

[ 5.   9.5 14.  18.5 23.  27.5 32.  36.5 41.  45.5]
4.5


2.6. Identity or Eye

np.eye() is a numpy function that creates a 2D array (matrix) with ones on the diagonal and zeros elsewhere. This matrix is known as an identity matrix when it's square (same number of rows and columns).

- np.eye(n)
- np.eye(n*m)
- np.eye(n*m, k)

    - n   - The number of rows (and columns for a square matrix)
    - m   - (optional) The number of columns. If not provided; it defaults to 'n', making a square matrix.
    - k   - (optional) The index of the diagonal to fill with ones. K=0 is the main diagonal, k>0 is above the main diagonal and k<0 is below the main diagonal.

In [196]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [197]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [198]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [199]:
np.eye(5,5,1)       # k=1

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [200]:
np.eye(5,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2.7. Diagonal

np.diag() function in numpy is used for two main purposes:

    - 1. Creating a diagonal matrix: When you pass a 1D array to np.diag(), it creates a 2D square matrix with the elements of the array on the main diagonal and zeros elsewhere.

    - np.diag(1d_array)

    - 2. Extracting diagonal elements: When you pass a 2D array (matrix) to np.diag(), it returns a 1D array containing the elements on the main diagonal of the matrix.

    - np.diag(2d_array)

In [201]:
a = np.array([1,2,3])
b = np.array([[1,2,3]])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [202]:
np.diag(a)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [203]:
np.diag(b)

array([1])

In [204]:
np.diag(c)

array([1, 5])

In [205]:
np.diag(d)

array([1, 5, 9])

2.8. Random

In [206]:
# Create a 1D array of random floats

np.random.rand(3)

array([0.1346327 , 0.91916604, 0.97590903])

In [207]:
# Create a 2D array of shape (3,3) with random floats

np.random.rand(3,3)

array([[0.33912012, 0.53258272, 0.69925257],
       [0.39444426, 0.55770097, 0.85272673],
       [0.2917386 , 0.15948783, 0.89848555]])

In [208]:
# Generate a single random integer from the uniform distribution over the interval [0,5].

np.random.randint(5)    # 5 is exclusive

4

In [209]:
# Create a 2D array of shape (3,4) with a normal distribution (mean=0, std=1)

np.random.randn(3,4)

array([[ 0.44477504, -0.6627326 , -0.98765735, -0.35244126],
       [-0.91779105, -0.10913867,  0.16165856,  2.45189898],
       [ 0.68522914, -0.59626617, -2.37447383,  1.78600055]])

### Array Attributes

In [210]:
a = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8]
        ],
        [
            [9, 10, 11, 12],
            [13, 14, 15, 16]
        ]
    ]
)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

N-Dimensional

np.ndim() is a function in numpy that returns the number of dimensions (or axis) of a given array. In other words, it tells you how many levels of depth an array has.

np.ndim(array)

In [211]:
np.ndim(a)          #Ans: 3, it means it is a 3-D array.

3

Shape

np.shape() is a function in numpy that returns the information about the size of each dimension (or axis) of the array.

np.shape(array)

In [212]:
np.shape(a)         #Ans: (2, 2, 3), it means it is a 3-D array with 2 blocks, 2 rows and 4 columns.

(2, 2, 4)

Size

np.size() is a function in numpy that returns the total number of elements in a given array.

np.size(array)

In [213]:
np.size(a)

16

Dtype

np.dtype() is a function in numpy that returns the data type of a numpy array.

print(array.dtype)

In [214]:
print(a.dtype)

int64


### Array Indexing and Slicing

You can index and slice numpy arrays in a similare way to python lists.

In [215]:
a = np.array([1, 2, 3, 4, 5])       
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])     
c = np.array([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]])       

##### *Indexing*

In [216]:
# fetch element:4

print(a[3])

4


In [217]:
# fetch element:5

print(b[1][1])

5


In [218]:
# fetch element:5

print(c[1][0][1])

5


##### *Slicing*

In [219]:
print(a[1:4])

[2 3 4]


In [220]:
print(b[1][1:])

[5 6]


In [221]:
print(c[1][0][1:])

[5 6]


### Adding and Sorting Elements

In [222]:
a = np.array(
    [
        [
            [1, 8, 6, 2],
            [5, 3, 7, 4]
        ],
        [
            [9, 16, 13, 10],
            [11, 12, 15, 14]
        ]
    ]
)
a

array([[[ 1,  8,  6,  2],
        [ 5,  3,  7,  4]],

       [[ 9, 16, 13, 10],
        [11, 12, 15, 14]]])

##### Sort

np.sort() is a function in numpy that returns a sorted copy of an array or sorts an array in place, depending upon the parameters used. It can sort the elements in ascending or descending order and can operate along different axes for multi-dimensional arrays.

np.sort(array, axis=-1)

    array   - The array to be sorted.
    axis    - The axis along which to sort. By default, it sorts along the axis (-1). If set to None, it sorts the entire array as a flattened array.

In [223]:
np.sort(a, axis=-1)

array([[[ 1,  2,  6,  8],
        [ 3,  4,  5,  7]],

       [[ 9, 10, 13, 16],
        [11, 12, 14, 15]]])

In [224]:
np.sort(a, axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

##### Concatenate

np.concatenate() is a function in numpy() that joins two or more arrays along a specified axis. It is useful for combining multiple arrays into single array.

np.concatenate((array1, array2, ...), axis=0)

    (array1, array2, ...)   - A sequence (like a tuple or list) or arrays you want to concatenate. All arrays must have the same shape along all axes, except the one you are concatenating along.
    axis        - The axis along which to concatenate the arrays. The default is 0, which means row-wise concatenate.

In [225]:
# Concatenating 1D arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [226]:
# Concatenating 2D arrays

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8, 9], [10, 11, 12]])

e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([[7, 8, 9]])

In [227]:
np.concatenate((c, d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [228]:
np.concatenate((c, d), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [229]:
np.concatenate((e, f))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Reshaping Array

np.reshape() is a function in numpy that allows you to change the shape of an existing array without changing its data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array.

np.reshape(array, newshape) 
or
array.reshape(newshape)

    array   - The input array you want to reshape.
    newshape- The desired shape of the output array. This can be specified as an integer or tuple of integers.

In [230]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
np.reshape(a, (5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [232]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [233]:
b = np.arange(16)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [234]:
np.reshape(b, (2, 2, 4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### Stacking Operations

In [235]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8, 9], [10, 11, 12]])

##### V-Stack

np.vstack() is a numpy function that stacks arrays vertically (row-wise). It takes sequence of arrays and joins them along a new vertical axis.

np.vstack((array1, array2))

In [236]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [237]:
np.vstack((c,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

##### H-Stack

np.hstack() is a numpy function that stacks arrays horizontally (column-wise). It takes sequence of arrays and joins them along new horizontal axis.

np.hstack((array1, array2))

In [238]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [239]:
np.hstack((c,d))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Basic Array Operations

In [240]:
a = np.array([7, 8, 9])
b = np.array([1, 2, 3])

##### *Addition*

In [241]:
a + b

array([ 8, 10, 12])

##### *Subtraction*

In [242]:
a - b

array([6, 6, 6])

##### *Multiplication*

In [243]:
a * b

array([ 7, 16, 27])

##### *Division*

In [244]:
a / b

array([7., 4., 3.])

##### *Modulo*

In [245]:
a % b

array([0, 0, 0])

##### *Floor Division*

In [246]:
a // b

array([7, 4, 3])

##### *Power*

In [247]:
a ** b

array([  7,  64, 729])

### Aggregate Functions

In [248]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]])

##### MAX

np.max() is a numpy function that returns the maximum value from an array or along a specified axis.

- np.max(array)
- np.max(array, axis=0)
- np.max(array, axis=1)

In [249]:
np.max(a)

np.int64(6)

In [250]:
np.max(a, axis=0)

array([4, 5, 6])

In [251]:
np.max(a, axis=1)

array([3, 6])

In [252]:
np.max(b)

np.int64(9)

In [253]:
np.max(b, axis=0)

array([[7, 8, 9]])

In [254]:
np.max(b, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### MIN

np.min() is a numpy function that returns the minimum value from an array or along a specified axis.

- np.min(array)
- np.min(array, axis=0)
- np.min(array, axis=1)

In [255]:
np.min(a)

np.int64(1)

In [256]:
np.min(a, axis=0)

array([1, 2, 3])

In [257]:
np.min(a, axis=1)

array([1, 4])

In [258]:
np.min(b)

np.int64(1)

In [259]:
np.min(b, axis=0)

array([[1, 2, 3]])

In [260]:
np.min(b, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### SUM

np.sum() is a numpy function that calculates the sum of array elements. It can be used to sum all elements in an array or along a specified axis.

- np.sum(array)
- np.sum(array, axis=0)
- np.sum(array, axis=1)

In [261]:
np.sum(a)

np.int64(21)

In [262]:
np.sum(a, axis=0)

array([5, 7, 9])

In [263]:
np.sum(a, axis=1)

array([ 6, 15])

In [264]:
np.sum(b)

np.int64(45)

In [265]:
np.sum(b, axis=0)

array([[12, 15, 18]])

In [266]:
np.sum(b, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### MEAN

np.mean() is a numpy function that calculates the average (arithmetic mean) of array elements. It can be used to compute the mean of all elements in an array or along a specified axis.

- np.mean(array)
- np.mean(array, axis=0)
- np.mean(array, axis=1)

In [267]:
np.mean(a)

np.float64(3.5)

In [268]:
np.mean(a, axis=0)

array([2.5, 3.5, 4.5])

In [269]:
np.mean(a, axis=1)

array([2., 5.])

In [270]:
np.mean(b)

np.float64(5.0)

In [271]:
np.mean(b, axis=0)

array([[4., 5., 6.]])

In [272]:
np.mean(b, axis=1)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

##### PRODUCT

np.prod() is a numpy function that calculates the product of array elements. It can be used to compute the product of all elements in an array or along a specified axis.

- np.prod(array)
- np.prod(array, axis=0)
- np.prod(array, axis=1)

In [273]:
np.prod(a)

np.int64(720)

In [274]:
np.prod(a, axis=0)

array([ 4, 10, 18])

In [275]:
np.prod(a, axis=1)

array([  6, 120])

In [276]:
np.prod(b)

np.int64(362880)

In [277]:
np.prod(b, axis=0)

array([[ 28,  80, 162]])

In [278]:
np.prod(b, axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### STANDARD DEVIATION

np.std() is a numpy function that calculates the standard deviation of array elements. 

- np.std(array)
- np.std(array, axis=0)
- np.std(array, axis=1)

In [279]:
np.std(a)

np.float64(1.707825127659933)

In [280]:
np.std(a, axis=0)

array([1.5, 1.5, 1.5])

In [281]:
np.std(a, axis=1)

array([0.81649658, 0.81649658])

In [282]:
np.std(b)

np.float64(2.581988897471611)

In [283]:
np.std(b, axis=0)

array([[2.44948974, 2.44948974, 2.44948974]])

In [284]:
np.std(b, axis=1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### VARIANCE

np.var() is a numpy function that calculates the variance of array elements.

- np.var(array)
- np.var(array, axis=0)
- np.var(array, axis=1)

In [285]:
np.var(a)

np.float64(2.9166666666666665)

In [286]:
np.var(a, axis=0)

array([2.25, 2.25, 2.25])

In [287]:
np.var(a, axis=1)

array([0.66666667, 0.66666667])

In [288]:
np.var(b)

np.float64(6.666666666666667)

In [289]:
np.var(b, axis=0)

array([[6., 6., 6.]])

In [290]:
np.var(b, axis=1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Trigonometric Functions

In [291]:
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
angles

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

##### SIN

np.sin() is a numpy function that calculates the sine of each element in the input array. The input should be in radians and the function returns the sine values corresponding to those angles. 

np.sin(array_of_angles(in radians))

In [292]:
np.sin(angles)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

##### COS

np.cos() is a numpy function that calculates the cosine of each element in the input array. The input should be in radians and the function returns the cosine values corresponding to those angles.

np.cos(array_of_angles(in radians))

In [293]:
np.cos(angles)

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

##### TAN

np.tan() is a numpy function that calculates the tangent of each element in the input array. The input should be in radians and the function returns the tangent values corresponding to those angles.

np.tan(array_of_angles(in radians))

In [294]:
np.tan(angles)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16,  5.44374645e+15,
       -2.44929360e-16])

### Flattening multi-dimensional arrays

In [295]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

##### 1. Flatten

The array.flatten() method is used to convert a multidimensional numpy array into a 1D array. It returns a copy of the orginal array flattened into a single dimension. The oroiginal array remains unchanged.

array.flatten()

In [296]:
x = a.flatten()
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [297]:
y = b.flatten()
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 2. Ravel

The array.ravel() method in numpy is used to flatten a multidimensional array into a 1D array. Unlike flatten(), which returns a copy, ravel() returns a flattened view of the array whenever possible, making it more memory efficient. The original array remains unchanged.

array.ravel()

In [298]:
x = a.ravel()
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [299]:
y = b.ravel()
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 3. Reshape

In [300]:
a.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [301]:
b.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Unique Items and Counts

The np.unique() function in numpy is used to find the unique elements of an array. It returns the sorted unique values from the input array and can also provide additional information about the indices and counts of these unique values.

np.unique(array, return_index=False, return_counts=False, axis=None)

    array           - The input array from which to find unique values.
    return_index    - (optional) If True, it returns the indices of the first occurrences of the unique values in the original array.
    return_counts   - (optional) If True, it returns the counts of each unique value.
    axis            - (optional) If specified, the unique values are found along ther axis. If None, the input array is flattened.

In [302]:
a = np.array([1,2,2,3,3,3,4,4,4,4,5,5,5,5,5])
b = np.array([[1,1,2],[3,5,3],[4,5,4],[4,5,5],[5,4,5]])
c = np.array([[[1,2,3],[3,2,1],[1,1,1]],[[2,2,2],[2,3,4],[1,2,3]],[[1,3,2],[3,3,3],[3,4,5]]])

In [303]:
unique_value, value_counts = np.unique(a, return_counts=True)
unique_value, value_counts

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [304]:
unique_value, value_counts = np.unique(b, return_counts=True)
unique_value, value_counts

(array([1, 2, 3, 4, 5]), array([2, 1, 2, 4, 6]))

In [305]:
unique_value, value_counts, index_position = np.unique(c, return_counts=True, return_index=True)
unique_value, value_counts, index_position

(array([1, 2, 3, 4, 5]), array([ 0,  1,  2, 14, 26]), array([7, 8, 9, 2, 1]))

In [306]:
unique_value, value_counts, index_position = np.unique(c, return_counts=True, return_index=True, axis=0)
unique_value, value_counts, index_position

(array([[[1, 2, 3],
         [3, 2, 1],
         [1, 1, 1]],
 
        [[1, 3, 2],
         [3, 3, 3],
         [3, 4, 5]],
 
        [[2, 2, 2],
         [2, 3, 4],
         [1, 2, 3]]]),
 array([0, 2, 1]),
 array([1, 1, 1]))

In [307]:
unique_value, value_counts, index_position = np.unique(b, return_counts=True, return_index=True, axis=1)
unique_value, value_counts, index_position

(array([[1, 1, 2],
        [3, 5, 3],
        [4, 5, 4],
        [4, 5, 5],
        [5, 4, 5]]),
 array([0, 1, 2]),
 array([1, 1, 1]))

### Index Retrieval Functions

In [308]:
a = np.array([5,4,3,2,1,0,10,9,8,7,6])
b = np.array([[1,2,3],[5,4,3],[7,8,9]])

##### 1. Nonzero

np.nonzero() returns the indices of the elements that are non-zero. It is useful for finding the non-zero elements in an array.

np.nonzero(array)

In [309]:
np.nonzero(a)

(array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10]),)

In [310]:
np.nonzero(b)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

##### 2. Where

np.where() returns the indices of elements that satisfies a given condition. It is useful for conditional indexing.

np.where(condition)

In [311]:
np.where(a>5)

(array([ 6,  7,  8,  9, 10]),)

In [312]:
np.where(b>5)

(array([2, 2, 2]), array([0, 1, 2]))

##### 3. Argmax

np.argmax() returns the index of the maximum value in an array. It is useful for finding the position of the largest element.

np.argmax(array)

In [313]:
np.argmax(a) 

np.int64(6)

In [314]:
np.argmax(b)

np.int64(8)

##### 4. Argmin

np.argmin() returns the index of the minimum value in an array. It is useful for finding the position of the smallest element.

np.argmin(array)

In [315]:
np.argmin(a)

np.int64(5)

In [316]:
np.argmin(b)

np.int64(0)

##### 5. Argsort

np.argsort() returns the indices that would sort an array. It is useful when you want to know the order of the elements in a sorted array.

np.argsort(array)

In [317]:
np.argsort(a)

array([ 5,  4,  3,  2,  1,  0, 10,  9,  8,  7,  6])

In [318]:
np.argsort(b)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]])